from pydantic import BaseModel, Field
from typing import List, Optional, Any, Union, Literal, Dict

class WorkflowState(BaseModel):
    """Global workflow state maintained in context."""
    user_goal: str = ""
    is_confirmed: bool = Field(False, description="Has the user explicitly confirmed the plan?")
    plan_steps: List[Dict[str, Any]] = Field(default_factory=list)
    current_step_index: int = 0
    completed_steps: List[str] = Field(default_factory=list)
    artifacts: List[str] = Field(default_factory=list)
    constraints: List[str] = Field(default_factory=list)
    notes: List[str] = Field(default_factory=list)

class TriageToPlanner(BaseModel):
    """Initial handoff from Triage to Planner."""
    user_goal: str = Field(..., description="The user's original request or goal.")
    current_state: str = Field("", description="Optional context about the current system state.")
    constraints: str = Field("", description="Any constraints mentioned by the user.")
    success_criteria: str = Field("", description="What defines a successful completion.")

class PlanStep(BaseModel):
    """A detailed step defined by the Planner."""
    step_id: str = Field(..., description="Unique ID for the step (e.g., '1', 'setup').")
    agent: str = Field(..., description="The specific MCP agent to execute this step (e.g. 'agent_sem').")
    goal: str = Field(..., description="High-level goal of this specific step.")
    skill: str = Field(..., description="The ID of the skill/playbook to use.")
    input: str = Field(..., description="Precise function call parameters, prompt, or technical action for this step.")
    expected_output: str = Field(..., description="Criteria for successful completion of this step.")
    on_success: str = Field(..., description="Next step ID to go to on success (e.g. '2') or 'done'.")
    on_failure: str = Field(..., description="Next step ID to go to on failure (e.g. 'stop') or 'ask user'.")

class Plan(BaseModel):
    """A list of PlanSteps generated by the Planner."""
    steps: List[PlanStep] = Field(..., description="The sequence of steps to achieve the goal.")

class ExecuteStepInput(BaseModel):
    """Instruction packet sent from Planner to Execute Agent."""
    step_id: str = Field(..., description="The ID of the step to execute.")
    agent: str = Field(..., description="The target specialist agent.")
    goal: str = Field(..., description="The specific goal for this step.")
    skill: str = Field(..., description="The skill or tool-set to be performed.")
    input: str = Field(..., description="Specific tool call parameters or prompts.")
    constraints: List[str] = Field(default_factory=list)

class ExecuteStepOutput(BaseModel):
    """Feedback from Execute Agent back to Planner."""
    status: Literal["success", "blocked", "failed"]
    result: str = Field(..., description="The natural language or data result of the execution.")
    artifacts: List[str] = Field(default_factory=list, description="Any files or data objects generated.")
    blocked_reason: Optional[str] = Field(None, description="Why the execution was blocked (if applicable).")
    next_recommendation: Optional[str] = Field(None, description="Suggestion for the next action if failed or blocked.")
